import fs from "fs";

//? Internal Environment Manager
const IEM_FILE = ".env.internal";

const IEM_HEADER = `
# This file is automatically managed by Waiter. Do not edit this file manually.
# It is used to store data managed by Waiter, such as encryption keys or tokens.
`.trim();


/**
 * @description Internal Environment Manager (IEM) for managing internal environment variables in a .env.internal file. This is used for storing sensitive data like encryption keys or tokens that should not be exposed in the main .env file.
 */
export const IEM = {
  get(key: string): string | undefined {
    if (!fs.existsSync(IEM_FILE)) return undefined;

    const data = fs.readFileSync(IEM_FILE, "utf-8");
    const lines = data.split("\n");
    for (const line of lines) {
      if (line.trim().startsWith("#")) continue;
      const [k, ...rest] = line.split("=");
      if (k.trim() === key.trim()) {
        let value = rest.join("=");
        // Remove surrounding quotes if present
        value = value.replace(/^(['"])(.+)\1$/, "$2");
        return value.trim();
      }
    }
    return undefined;
  },

  set(key: string, value: string) {
    let data = "";
    key = key.trim();
    value = value.trim();
    if (fs.existsSync(IEM_FILE)) {
      data = fs.readFileSync(IEM_FILE, "utf-8");
      const lines = data.split("\n");
      let found = false;
      for (let i = 0; i < lines.length; i++) {
        if (lines[i].trim().startsWith("#") || !lines[i].trim()) continue;
        const [k] = lines[i].split("=");
        if (k.trim() === key.trim()) {
          lines[i] = `${key.trim()}="${value}"`;
          found = true;
          break;
        }
      }
      if (!found) {
        lines.push(`${key.trim()}="${value}"`);
      }
      data = lines.join("\n");
    } else {
      data = `${IEM_HEADER}\n\n${key.trim()}="${value}"`;
    }
    fs.writeFileSync(IEM_FILE, data, "utf-8");
  },

  delete(...keys: string[]) {
    if (!fs.existsSync(IEM_FILE)) return;

    let data = fs.readFileSync(IEM_FILE, "utf-8");
    const lines = data.split("\n");
    const newLines = lines.filter((line) => {
      if (line.trim().startsWith("#") || !line.trim()) return true;
      const [k] = line.split("=");
      return !keys.includes(k.trim());
    });
    data = newLines.join("\n");
    fs.writeFileSync(IEM_FILE, data, "utf-8");
  },

  clear() {
    if (fs.existsSync(IEM_FILE)) {
      fs.unlinkSync(IEM_FILE);
    }
  },
};
